apiVersion: apps/v1
kind: Deployment
metadata:
  name: docx-to-pdf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docx-to-pdf
  template:
    metadata:
      labels:
        app: docx-to-pdf
    spec:
      containers:
      - name: docx-to-pdf
        image: your-docker-username/docx-to-pdf:latest
        ports:
        - containerPort: 5000
